name: PacerID

options:
  bundleIdPrefix: com.plabrum
  deploymentTarget:
    iOS: "16.0"
  developmentLanguage: en
  xcodeVersion: "15.0"
  groupSortPosition: top
  generateEmptyDirectories: true
  useBaseInternationalization: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    SWIFT_STRICT_CONCURRENCY: complete
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: "AH7U25NYNS"
    ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
    SWIFT_EMIT_LOC_STRINGS: YES
    ENABLE_USER_SCRIPT_SANDBOXING: YES
    GENERATE_INFOPLIST_FILE: NO

targets:
  PacerID:
    type: application
    platform: iOS

    sources:
      - path: PacemakerID
        excludes:
          - "*.md"
          - "*.txt"
      - path: ../ml/models/current
        optional: true

    info:
      path: PacemakerID/Info.plist
      properties:
        CFBundleDevelopmentRegion: $(DEVELOPMENT_LANGUAGE)
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: $(PRODUCT_NAME)
        CFBundleDisplayName: Pacer-ID
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        LSRequiresIPhoneOS: true
        NSCameraUsageDescription: "Pacer-ID needs camera access to photograph X-rays and identify pacemaker devices."
        UILaunchScreen: {}
        UIRequiredDeviceCapabilities:
          - armv7
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight

    settings:
      base:
        PRODUCT_NAME: PacerID
        PRODUCT_BUNDLE_IDENTIFIER: com.plabrum.PacerID
        INFOPLIST_FILE: PacemakerID/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1,2" # iPhone and iPad
        SWIFT_EMIT_LOC_STRINGS: YES
        ENABLE_PREVIEWS: YES
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG

      debug:
        SWIFT_OPTIMIZATION_LEVEL: "-Onone"
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG

      release:
        SWIFT_OPTIMIZATION_LEVEL: "-O"
        SWIFT_COMPILATION_MODE: wholemodule

    scheme:
      testTargets:
        - PacerIDTests
        - PacerIDIntegrationTests
        - PacerIDUITests
      gatherCoverageData: true

    dependencies: []

  # Unit Tests
  PacerIDTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: PacemakerIDTests
        excludes:
          - "*.md"
    dependencies:
      - target: PacerID
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.plabrum.PacerIDTests
        TARGETED_DEVICE_FAMILY: "1,2"
        GENERATE_INFOPLIST_FILE: YES
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/PacerID.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/PacerID"
        BUNDLE_LOADER: "$(TEST_HOST)"
    scheme:
      gatherCoverageData: true

  # Integration Tests
  PacerIDIntegrationTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: PacemakerIDIntegrationTests
        excludes:
          - "*.md"
    dependencies:
      - target: PacerID
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.plabrum.PacerIDIntegrationTests
        TARGETED_DEVICE_FAMILY: "1,2"
        GENERATE_INFOPLIST_FILE: YES
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/PacerID.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/PacerID"
        BUNDLE_LOADER: "$(TEST_HOST)"
    scheme:
      gatherCoverageData: true

  # UI Tests
  PacerIDUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: PacemakerIDUITests
        excludes:
          - "*.md"
    dependencies:
      - target: PacerID
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.plabrum.PacerIDUITests
        TARGETED_DEVICE_FAMILY: "1,2"
        GENERATE_INFOPLIST_FILE: YES
        TEST_TARGET_NAME: PacerID
    scheme:
      gatherCoverageData: true

schemes:
  PacerID:
    build:
      targets:
        PacerID: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - PacerIDTests
        - PacerIDIntegrationTests
        - PacerIDUITests
      gatherCoverageData: true
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
